//
//  MessagesViewController.swift
//  Stickeroid MessagesExtension
//
//  Created by Vadym Sidorov on 9/13/18.
//  Copyright © 2018 Vadym Sidorov. All rights reserved.
//

import UIKit
import Messages

class MessagesViewController: MSMessagesAppViewController, UICollectionViewDataSource, UICollectionViewDelegate, UISearchBarDelegate {
    
    var lastQueryStickerUrls: [StickerURL]?
    
    @IBOutlet weak var stickerCollectionView: UICollectionView!
    @IBOutlet weak var searchBar: UISearchBar!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        searchBar.delegate = self
        setupCollectionView()
    }
    
    override func didTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        if presentationStyle == .expanded {
            searchBar.becomeFirstResponder()
        }
    }
    
    func setupCollectionView() {
        stickerCollectionView.register(UINib(nibName: "StickerCell", bundle: .main), forCellWithReuseIdentifier: UIConstants.CellReusabilityIdentifier)
        stickerCollectionView.dataSource = self
        stickerCollectionView.delegate = self
    }
    
    func performSearch(searchQuery: String) {
        lastQueryStickerUrls = nil
        stickerCollectionView.reloadData()
        
        Request.getStickerURLsFor(searchQuery: searchQuery,
                                  numberOfStickers: RequestConstants.ItemsPerRequest) { [weak self] (_ urls: [StickerURL]) in
                                    self?.lastQueryStickerUrls = urls
                                    
                                    DispatchQueue.main.async { [weak self] in
                                        self?.stickerCollectionView.reloadData()
                                    }
        }
    }
}

extension MessagesViewController {
    func searchBarTextDidBeginEditing(_ searchBar: UISearchBar) {
        requestPresentationStyle(.expanded)
    }
    
    func searchBarSearchButtonClicked(_ searchBar: UISearchBar) {
        if let query = searchBar.text {
            performSearch(searchQuery: query)
        }
    }
}
    
//    override func didReceiveMemoryWarning() {
//        super.didReceiveMemoryWarning()
//        // Dispose of any resources that can be recreated.
//    }
//
//    // MARK: - Conversation Handling
//    override func willBecomeActive(with conversation: MSConversation) {
//        // Called when the extension is about to move from the inactive to active state.
//        // This will happen when the extension is about to present UI.
//
//        // Use this method to configure the extension and restore previously stored state.
//    }
//
//    override func didResignActive(with conversation: MSConversation) {
//        // Called when the extension is about to move from the active to inactive state.
//        // This will happen when the user dissmises the extension, changes to a different
//        // conversation or quits Messages.
//
//        // Use this method to release shared resources, save user data, invalidate timers,
//        // and store enough state information to restore your extension to its current state
//        // in case it is terminated later.
//    }
//
//    override func didReceive(_ message: MSMessage, conversation: MSConversation) {
//        // Called when a message arrives that was generated by another instance of this
//        // extension on a remote device.
//
//        // Use this method to trigger UI updates in response to the message.
//    }
//
//    override func didStartSending(_ message: MSMessage, conversation: MSConversation) {
//        // Called when the user taps the send button.
//    }
//
//    override func didCancelSending(_ message: MSMessage, conversation: MSConversation) {
//        // Called when the user deletes the message without sending it.
//
//        // Use this to clean up state related to the deleted message.
//    }
//}

